const mongoose = require('mongoose'); 
const bookingSchema = new mongoose.Schema({
    theatreId:{
        type:mongoose.SchemaTypes.ObjectId,
        required:true,
        ref:"Theatre"
    },
    movieId:{
        type:mongoose.SchemaTypes.ObjectId,
        required:true,
        ref:"Movie"
    },
    userId:{
        type:mongoose.SchemaTypes.ObjectId,
        require:true,
        ref:"User"
    },
    status:{
     type:String,
     require:true,
     default:"IN-PROGRESS"
    },
    noOfSeats:{
        type:Number,
        required:true,
    },
    totalCost:{
        type:Number,
    }
})